export const KINGDOM_COLORS = ["#4da3ff", "#f06a6a", "#e6b450", "#7bd88f", "#6f7888"];

export const BUILD_DEFS = {
  wall: {
    id: "wall",
    name: "Wall",
    group: "defense",
    cost: 8,
    hp: 120,
    size: 30,
    blocks: true,
    desc: "High HP blocker. Slows and distracts nearby attackers.",
  },
  tower: {
    id: "tower",
    name: "Tower",
    group: "defense",
    cost: 20,
    hp: 90,
    size: 34,
    range: 150,
    damage: 9,
    cooldown: 0.9,
    shot: "arrow",
    desc: "Long range shots. Reliable single-target defense.",
  },
  beam_obelisk: {
    id: "beam_obelisk",
    name: "Beam Obelisk",
    group: "defense",
    cost: 34,
    hp: 85,
    size: 36,
    range: 190,
    damage: 14,
    cooldown: 1.35,
    shot: "beam",
    tech: "beam_obelisk",
    desc: "Unlock. Piercing beam that cuts through a line of attackers.",
  },
  nova_shrine: {
    id: "nova_shrine",
    name: "Nova Shrine",
    group: "defense",
    cost: 32,
    hp: 95,
    size: 38,
    range: 105,
    damage: 10,
    cooldown: 2.4,
    shot: "nova",
    tech: "nova_shrine",
    desc: "Unlock. Ring pulse that damages and slows nearby attackers.",
  },
  barracks: {
    id: "barracks",
    name: "Barracks",
    group: "defense",
    cost: 24,
    hp: 150,
    size: 42,
    spawn: "guard",
    spawnCount: 2,
    desc: "Spawns two guards. Guards intercept enemies near the core.",
  },
  trap: {
    id: "trap",
    name: "Trap",
    group: "defense",
    cost: 12,
    hp: 1,
    size: 28,
    damage: 45,
    singleUse: true,
    desc: "One-use explosive. Huge burst when enemies cross it.",
  },
  farm: {
    id: "farm",
    name: "Farm",
    group: "economy",
    cost: 22,
    hp: 70,
    size: 38,
    income: 5,
    desc: "Adds income each round. Weak in battle.",
  },
  guard_post: {
    id: "guard_post",
    name: "Guard Post",
    group: "defense",
    cost: 14,
    hp: 75,
    size: 32,
    spawn: "guard",
    spawnCount: 1,
    desc: "Spawns one guard. Cheap defensive body.",
  },
  raider_camp: {
    id: "raider_camp",
    name: "Raider Camp",
    group: "offense",
    cost: 18,
    hp: 70,
    size: 36,
    army: "raider",
    armyCount: 3,
    desc: "Adds fast raiders. Raiders sprint and attack quickly.",
  },
  ranger_range: {
    id: "ranger_range",
    name: "Ranger Range",
    group: "offense",
    cost: 26,
    hp: 75,
    size: 38,
    army: "ranger",
    armyCount: 2,
    tech: "ranger_range",
    desc: "Unlock. Adds ranged attackers with spread shots.",
  },
  arcanum: {
    id: "arcanum",
    name: "Arcanum",
    group: "offense",
    cost: 34,
    hp: 82,
    size: 40,
    army: "mage",
    armyCount: 2,
    tech: "arcanum",
    desc: "Unlock. Adds beam casters that pierce defender lines.",
  },
  knight_stable: {
    id: "knight_stable",
    name: "Stable",
    group: "offense",
    cost: 28,
    hp: 95,
    size: 40,
    army: "knight",
    armyCount: 2,
    desc: "Adds knights. Knights are armored and charge into melee.",
  },
  siege_yard: {
    id: "siege_yard",
    name: "Siege Yard",
    group: "offense",
    cost: 36,
    hp: 110,
    size: 44,
    army: "siege",
    armyCount: 1,
    desc: "Adds siege. Siege fires splash shots and crushes cores.",
  },
};

export const UNIT_DEFS = {
  guard: { name: "Guard", role: "Intercepter", hp: 64, armor: 1, speed: 58, damage: 8, range: 28, cooldown: 0.72, radius: 10, special: "Holds attackers near the core." },
  archer: { name: "Archer", role: "Ranged", hp: 36, armor: 0, speed: 48, damage: 7, range: 132, cooldown: 0.95, radius: 9, slow: 0.25, special: "Arrows briefly slow targets." },
  raider: { name: "Raider", role: "Fast melee", hp: 42, armor: 0, speed: 82, damage: 7, range: 22, cooldown: 0.58, radius: 9, special: "Sprints toward buildings and attacks fast." },
  knight: { name: "Knight", role: "Armored charge", hp: 90, armor: 2, speed: 58, damage: 12, range: 24, cooldown: 0.84, radius: 11, charge: 1.8, special: "First hit after moving is a charge." },
  siege: { name: "Siege", role: "Splash siege", hp: 150, armor: 1, speed: 34, damage: 28, range: 86, cooldown: 1.9, radius: 15, splash: 42, special: "Slow splash shots punish clusters and cores." },
  ranger: { name: "Ranger", role: "Spread shot", hp: 44, armor: 0, speed: 54, damage: 6, range: 132, cooldown: 1.05, radius: 9, spread: 3, special: "Fires a three-arrow spread." },
  mage: { name: "Mage", role: "Beam caster", hp: 38, armor: 0, speed: 46, damage: 11, range: 150, cooldown: 1.55, radius: 9, beam: true, special: "Piercing beam attack." },
};

export const FORMATIONS = {
  line: {
    id: "line",
    name: "Line",
    desc: "Wide front. Good for surrounding defenses.",
  },
  wedge: {
    id: "wedge",
    name: "Wedge",
    desc: "Focused push. Good for punching toward the core.",
  },
  column: {
    id: "column",
    name: "Column",
    desc: "Compact stack. Good for protecting siege.",
  },
  scatter: {
    id: "scatter",
    name: "Scatter",
    desc: "Loose entry. Good against traps and beams.",
  },
};

export const TECH_DEFS = {
  reinforced_masonry: {
    id: "reinforced_masonry",
    name: "Reinforced Masonry",
    desc: "All current and future structures gain +30 max HP.",
    apply: "structure_hp",
    amount: 30,
  },
  sharper_arrows: {
    id: "sharper_arrows",
    name: "Sharper Arrows",
    desc: "Towers, archers, and rangers deal +3 damage.",
    apply: "arrow_damage",
    amount: 3,
  },
  war_drills: {
    id: "war_drills",
    name: "War Drills",
    desc: "All offensive units gain +15% speed.",
    apply: "offense_speed",
    amount: 0.15,
  },
  veteran_guards: {
    id: "veteran_guards",
    name: "Veteran Guards",
    desc: "Guard defenders gain +20 HP and +2 damage.",
    apply: "guard_veterans",
  },
  factory_crews: {
    id: "factory_crews",
    name: "Factory Crews",
    desc: "Gain +2 permanent workers in your factory.",
    apply: "factory_workers",
    amount: 2,
  },
  precision_machining: {
    id: "precision_machining",
    name: "Precision Machining",
    desc: "Gain +1 machine and +0.10 factory quality.",
    apply: "factory_machines",
  },
  courier_guild: {
    id: "courier_guild",
    name: "Courier Guild",
    desc: "Gain +2 logistics. Factory workers deliver parts faster.",
    apply: "factory_logistics",
    amount: 2,
  },
  anti_sabotage: {
    id: "anti_sabotage",
    name: "Anti-Sabotage Office",
    desc: "Sabotage against your factory hurts less and expires faster.",
    apply: "anti_sabotage",
  },
  beam_obelisk: {
    id: "beam_obelisk",
    name: "Unlock Beam Obelisk",
    desc: "Unlocks a piercing defensive beam building.",
    apply: "unlock_building",
    building: "beam_obelisk",
  },
  nova_shrine: {
    id: "nova_shrine",
    name: "Unlock Nova Shrine",
    desc: "Unlocks a pulsing ring-damage defensive building.",
    apply: "unlock_building",
    building: "nova_shrine",
  },
  ranger_range: {
    id: "ranger_range",
    name: "Unlock Ranger Range",
    desc: "Unlocks offensive rangers with spread shots.",
    apply: "unlock_building",
    building: "ranger_range",
  },
  arcanum: {
    id: "arcanum",
    name: "Unlock Arcanum",
    desc: "Unlocks offensive mages with piercing beams.",
    apply: "unlock_building",
    building: "arcanum",
  },
};

export const BOARD_NODES = [
  { id: "n0", name: "Northwatch", income: 4, x: 0.22, y: 0.28 },
  { id: "n1", name: "Ironford", income: 6, x: 0.43, y: 0.20 },
  { id: "n2", name: "Sunspire", income: 8, x: 0.63, y: 0.25 },
  { id: "n3", name: "Ashgate", income: 5, x: 0.78, y: 0.40 },
  { id: "n4", name: "Goldmere", income: 9, x: 0.63, y: 0.58 },
  { id: "n5", name: "Stonehook", income: 5, x: 0.42, y: 0.64 },
  { id: "n6", name: "Greenbarrow", income: 4, x: 0.20, y: 0.55 },
  { id: "n7", name: "Crown Crossing", income: 10, x: 0.50, y: 0.41 },
  { id: "n8", name: "Mossfield", income: 6, x: 0.34, y: 0.42 },
  { id: "n9", name: "Red Bridge", income: 7, x: 0.68, y: 0.43 },
  { id: "n10", name: "Deepmarket", income: 8, x: 0.52, y: 0.79 },
  { id: "n11", name: "Stormmill", income: 7, x: 0.84, y: 0.67 },
];

export const BOARD_EDGES = [
  ["n0", "n1"], ["n1", "n2"], ["n2", "n3"], ["n3", "n9"],
  ["n9", "n4"], ["n4", "n5"], ["n5", "n6"], ["n6", "n0"],
  ["n0", "n8"], ["n8", "n7"], ["n7", "n9"], ["n7", "n4"],
  ["n8", "n5"], ["n2", "n7"], ["n5", "n10"], ["n4", "n10"],
  ["n3", "n11"], ["n4", "n11"],
];
