// GENERATED by art/vehicles/author_vehicles.py (npm run art:vehicles) — do not edit.
// Each vehicles-kit part's authored bounding box in GAME units (x right, y up, z forward):
// the kit mesh is a unit cube, so box(..., { geometry }) with this size at this centre puts
// the part back exactly where it was authored. Shape AND proportion live in Blender for
// vehicles — the parts of one hull have to fit each other.
import type { VehiclesPart } from "./models";

export const VEHICLE_LAYOUT: Record<VehiclesPart, { size: [number, number, number]; center: [number, number, number] }> = {
  "apc-autogun": { size: [0.37, 0.18, 1.19], center: [0.035, 2.13, 0.755] },
  "apc-cupola": { size: [0.6467, 0.48, 0.69], center: [0.0, 2.11, 0.125] },
  "apc-front": { size: [1.8, 1.0202, 0.6348], center: [0.0, 0.7601, 1.3] },
  "apc-hull": { size: [1.96, 1.68, 2.8774], center: [0.0, 1.25, -0.0387] },
  "apc-wheels": { size: [0.5, 0.9, 2.86], center: [0.0, 0.45, -0.0] },
  "arty-front": { size: [2.2, 0.8717, 0.6603], center: [0.0, 0.5361, 1.4802] },
  "arty-gun": { size: [0.54, 1.667, 3.086], center: [0.0, 1.9885, 0.6054] },
  "arty-hull": { size: [2.4, 1.223, 3.3013], center: [0.0, 0.7585, -0.2506] },
  "arty-mount": { size: [1.48, 0.87, 1.48], center: [0.0, 1.415, -0.25] },
  "arty-track": { size: [0.62, 0.72, 3.114], center: [0.0, 0.42, -0.207] },
  "barricade": { size: [1.9, 0.92, 0.7354], center: [0.0, 0.46, -0.2277] },
  "crates": { size: [1.7228, 1.34, 1.0373], center: [0.0814, 0.64, -0.0186] },
  "hq-comms": { size: [0.66, 1.9, 0.6145], center: [-0.92, 2.6, -0.0627] },
  "hq-core": { size: [3.0, 2.53, 2.6], center: [0.0, 1.265, -0.0] },
  "hq-gate": { size: [2.7, 1.06, 0.55], center: [0.0, 0.63, 1.285] },
  "hq-power": { size: [0.84, 1.26, 0.7], center: [1.0, 1.17, -0.72] },
  "sandbags": { size: [1.6569, 0.5575, 0.7135], center: [-0.0019, 0.2987, -0.0009] },
  "tank-cannon": { size: [0.2853, 0.3, 1.9], center: [0.0, 1.38, 1.7] },
  "tank-front": { size: [2.3, 0.7795, 0.6044], center: [0.0, 0.7297, 1.42] },
  "tank-hull": { size: [2.46, 1.08, 3.1], center: [0.0, 0.83, -0.15] },
  "tank-track": { size: [0.62, 0.83, 3.02], center: [0.0, 0.475, 0.01] },
  "tank-turret": { size: [1.57, 0.65, 2.02], center: [0.005, 1.435, -0.02] },
  "turret-gun": { size: [1.13, 0.6, 2.01], center: [0.065, 0.97, 0.505] },
  "turret-mount": { size: [1.8, 0.7, 1.8], center: [0.0, 0.35, -0.0] },
  "turret-sensor": { size: [0.32, 0.63, 0.32], center: [-0.34, 1.535, -0.14] },
};
